config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :line_items
  resources :carts
  resources :products do
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_item.find_by(product_id: product.id)
    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price}
  end





end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :products
  belongs_to :carts
  validates :quantity, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :products
  belongs_to :cart

  def total_price
    product.price.to_i * quantity.to_i
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :users
  belongs_to :carts
end

app/models/product.rb
class Product < ApplicationRecord
    before_destroy :not_referenced_by_any_line_item
    has_many :line_items, dependent: :destroy
    has_many_attached :images, dependent: :destroy

    private

    def not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, "Line items present")
            throw :abort
        end
    end

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :products
  belongs_to :categories
end

app/models/product_price.rb
class ProductPrice < ApplicationRecord
  belongs_to :products
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         has_many :carts, dependent: :destroy
         has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include CurrentCart
  before_action :set_cart

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :set_cart, only: [:show, :edit, :update,:destroy]

def index
end

def show
end

def new
end

def edit
end

def create
end

def update
end

def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    redirect_to carts_url, notice: "Cart was succesfully destroyed."
end

private

def set_cart
    @cart = Cart.find(params[:id])
end

def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_path, notice: "That cart doesn't exist"
end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
    include CurrentCart
    before_action :set_line_item, only: [:show, :edit, :update, :destroy]
    before_action :set_cart, only: [:create]

    def index
    end

    def show
    end

    def new
    end

    def edit
    end

    def create
        product = Product.find(params[:product_id])
        @line_item = @cart.add_instrument(product)
        if @line_item.save
            redirect_to @line_item.cart, notice: 'Item added to cart.'
        else
            render :new
        end
    end

    def update
    end

    def destroy
        @cart = Cart.find(session[:cart_id])
        @line_item.destroy
        redirect_to cart_path(@cart), notice: 'Producto eliminado'
    end

    private

    def set_line_item
        @line_item = LineItem.find(params[:id])
    end

    def line_item_params
        params.require(:line_item).permit(:product_id)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
end

app/controllers/product_prices_controller.rb
class ProductPricesController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    skip_before_action :authenticate_user!, :only => [:index]
    def index
    end
end

app/controllers/stock_controller.rb
class StockController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/show.html.erb
<%= render 'shared/navbar' %>

<div class="big-container">
    <div class="main-container">
        <div class="cart-content">
            <div class="cart-card">
                <img src="https://res.cloudinary.com/dqstmox0s/image/upload/v1600957640/Components/photo-1555507036-ab1f4038808a_c6ef0k.jpg" alt="">
                <div class="first-part">
                    <h4>Desayuno para 2</h4>
                    <p>quitar</p>
                </div>
                <div class="second-part">
                    <h4 class="quantity">1</h4>
                    <h4 class="cart-card-price">16,20 €</h4>
                </div>
            </div>
            <div class="line-separator"></div>
            <div class="cart-card">
                <img src="https://res.cloudinary.com/dqstmox0s/image/upload/v1600957642/Components/photo-1587339144367-f1cacbecac82_uimzwz.jpg" alt="">
                <div class="first-part">
                    <h4>Desayuno para 2</h4>
                    <p>quitar</p>
                </div>
                <div class="second-part">
                    <h4 class="quantity">1</h4>
                    <h4 class="cart-card-price">16,20 €</h4>
                </div>
            </div>
            <div class="line-separator"></div>
            <div class="cart-card">
                <img src="https://res.cloudinary.com/dqstmox0s/image/upload/v1600958432/Components/photo-1572928899385-6dc3b05531ce_vkbr3u.jpg" alt="">
                <div class="first-part">
                    <h4>Desayuno para 2</h4>
                    <p>quitar</p>
                </div>
                <div class="second-part">
                    <h4 class="quantity">1</h4>
                    <h4 class="cart-card-price">16,20 €</h4>
                </div>
            </div>
            <div class="line-separator"></div>
            <div class="cart-card">
                <img src="https://res.cloudinary.com/dqstmox0s/image/upload/v1600958432/Components/photo-1572928899385-6dc3b05531ce_vkbr3u.jpg" alt="">
                <div class="first-part">
                    <h4>Desayuno para 2</h4>
                    <p>quitar</p>
                </div>
                <div class="second-part">
                    <h4 class="quantity">1</h4>
                    <h4 class="cart-card-price">16,20 €</h4>
                </div>
            </div>
            <div class="line-separator"></div>
            <div class="total-cart">
            <h3 class="total">Total</h3>
            <h3 class="total-price">81,00 €</h3>
            </div>
        </div>
        <%= link_to "Tramitar pedido",products_path , class: "large-button mt-3 mb-2"%>
    </div>
</div>

app/views/products/index.html.erb
<%= render 'shared/navbar' %> 

<%# -------> TABS <------- %>

<div class="big-container">
  <div class="products">
  <div class="tabs-sticky">
    <div class="products__tab-container">
      <a class="products__tab products__tab--1 products__tab--active" data-tab="1"
        ><h4>Desayunos</h4></a>
      <a class="products__tab products__tab--2" data-tab="2"><h4>Buffet</h4></a>
      <a class="products__tab products__tab--3" data-tab="3"><h4>Bandejas</h4></a>
    </div>
  </div>

    <div class="products__content products__content--1 products__content--active">
      <div class="product-card-container">
        <div class="btn-card">
          <img src="https://res.cloudinary.com/dqstmox0s/image/upload/v1600945856/Components/05_ALC_coffret_de_8_mini_viennoiseries_2_900x_s2ihr3.jpg" alt="Croissant" class=product-card-img>
          <button class="circle-btn">+</button>
        </div>
        <div class="product-card-h3">
            <h3>Desayuno individual</h3>
            <p>Celebra a tus clientes, reconoce a tus empleados, y promueve la cultura de la empresa</p>
            <div class="price">
              <h3>16,20 €</h3>
            </div>
        </div> 
      </div>
      <div class="product-card-container">
        <div class="btn-card">
          <img src="https://res.cloudinary.com/dqstmox0s/image/upload/v1601305775/Components/offre-a-la-carte_f0dr5r.jpg" alt="Croissant" class=product-card-img>
          <button class="circle-btn">+</button>
        </div>
        <div class="product-card-h3">
            <h3>Regalos corporativos</h3>
            <p>Celebra a tus clientes, reconoce a tus empleados, y promueve la cultura de la empresa</p>
            <div class="price">
              <h3>16,20 €</h3>
            </div>
        </div> 
      </div>
      <div class="product-card-container">
        <div class="btn-card">
          <img src="https://res.cloudinary.com/dqstmox0s/image/upload/v1600945850/Components/bread-1284438-1920_derylj.jpg" alt="Croissant" class=product-card-img>
          <button class="circle-btn">+</button>
        </div>
        <div class="product-card-h3">
            <h3>Regalos corporativos</h3>
            <p>Celebra a tus clientes, reconoce a tus empleados, y promueve la cultura de la empresa</p>
            <div class="price">
              <h3>16,20 €</h3>
            </div>
        </div> 
      </div>
    </div>
    <div class="products__content products__content--2">
      <div class="product-card-container">
        <div class="btn-card">
          <img src="https://res.cloudinary.com/dqstmox0s/image/upload/v1600945850/Components/bread-1284438-1920_derylj.jpg" alt="Croissant" class=product-card-img>
          <button class="circle-btn">+</button>
        </div>
        <div class="product-card-h3">
            <h3>Buffet a domicilio</h3>
            <p>Celebra a tus clientes, reconoce a tus empleados, y promueve la cultura de la empresa</p>
            <div class="price">
              <h3>16,20 €</h3>
            </div>
        </div> 
      </div>
      <div class="product-card-container">
        <div class="btn-card">
          <img src="https://res.cloudinary.com/dqstmox0s/image/upload/v1600958432/Components/photo-1572928899385-6dc3b05531ce_vkbr3u.jpg" alt="Croissant" class=product-card-img>
          <button class="circle-btn">+</button>
        </div>
        <div class="product-card-h3">
            <h3>Regalos corporativos</h3>
            <p>Celebra a tus clientes, reconoce a tus empleados, y promueve la cultura de la empresa</p>
            <div class="price">
              <h3>16,20 €</h3>
            </div>
        </div> 
      </div>
      <div class="product-card-container">
        <div class="btn-card">
          <img src="https://res.cloudinary.com/dqstmox0s/image/upload/v1601305775/Components/offre-a-la-carte_f0dr5r.jpg" alt="Croissant" class=product-card-img>
          <button class="circle-btn">+</button>
        </div>
        <div class="product-card-h3">
            <h3>Regalos corporativos</h3>
            <p>Celebra a tus clientes, reconoce a tus empleados, y promueve la cultura de la empresa</p>
            <div class="price">
              <h3>16,20 €</h3>
            </div>
        </div> 
      </div>
    </div>
    <div class="products__content products__content--3">
      <div class="product-card-container">
        <div class="btn-card">
          <img src="https://res.cloudinary.com/dqstmox0s/image/upload/v1600957642/Components/photo-1587339144367-f1cacbecac82_uimzwz.jpg" alt="Croissant" class=service-card-img>
          <button class="circle-btn">+</button>
        </div>
        <div class="product-card-h3">
            <h3>Pancakes</h3>
            <p>Celebra a tus clientes, reconoce a tus empleados, y promueve la cultura de la empresa</p>
            <div class="price">
              <h3>16,20 €</h3>
            </div>
        </div> 
      </div>
      <div class="product-card-container">
        <div class="btn-card">
          <img src="https://res.cloudinary.com/dqstmox0s/image/upload/v1600946425/Components/photo-1579306194872-64d3b7bac4c2_ubwlrk.jpg" alt="Croissant" class=product-card-img>
          <button class="circle-btn">+</button>
        </div>
        <div class="product-card-h3">
            <h3>Regalos corporativos</h3>
            <p>Celebra a tus clientes, reconoce a tus empleados, y promueve la cultura de la empresa</p>
            <div class="price">
              <h3>16,20 €</h3>
            </div>
        </div> 
      </div>
      <div class="product-card-container">
        <div class="btn-card">
          <img src="https://res.cloudinary.com/dqstmox0s/image/upload/v1600957640/Components/photo-1555507036-ab1f4038808a_c6ef0k.jpg" alt="Croissant" class=product-card-img>
          <button class="circle-btn">+</button>
        </div>
        <div class="product-card-h3">
            <h3>Regalos corporativos</h3>
            <p>Celebra a tus clientes, reconoce a tus empleados, y promueve la cultura de la empresa</p>
            <div class="price">
              <h3>16,20 €</h3>
            </div>
        </div> 
      </div>
    </div>

  </div>
  <div id="mainDiv">
    <div id="borderLeft"></div>
  </div>
</div>

<%= render 'shared/footer' %> 

app/views/products/show.html.erb
<%= render 'shared/navbar' %>
<div class="big-container">
    <img src="https://res.cloudinary.com/dqstmox0s/image/upload/v1601305775/Components/offre-a-la-carte_f0dr5r.jpg" alt="Croissant" class=show-img>
    <div class="product-show">
        <div class="main-container">
            <div class="product-description">
                <h3>Desayuno individual</h3>
                <p>2 Media lunas, degustación de nuestras tartas, pancakes con sirope de arce y frutos rojos, y café frío a gusto.</p>
                <div class="quantity-ui">
                    <button class="circle-small-btn circle-minus-btn">-</button>
                    <h3>1</h3>
                    <button class="circle-small-btn circle-plus-btn">+</button>
                </div>
                <div class="price">
                    <h3>16,20 €</h3>
                </div>
            </div>
        </div>
            <div class="main-container">
                <%= link_to "Añadir al carrito",products_path , class: "large-button"%>
            </div>
    </div>
</div>